### ISSUE TITLE
FileUpload ricerca media library: invece della struttura Loopback standard (filter) passare il testo come parametro "search" stringa

### ISSUE THREAD

**Issue by lucamussoni** [MrAPPs-RSM/ngx-backend#124]

**Comment by lucamussoni** [comment]
in più passare campi "page" e "perPage" per la paginazione

oppure definiamo una struttura "filter" con meno campi?

**Comment by damiandominella** [comment]
@lucamussoni 

Struttura chiamata: 

```json
{
  "types": ["image/jpeg", "image/png"],
  "page": 1,
  "perPage": 12,
  "search": null,
  "skipIds": [1,2,3]
}
```

Descrizione:

**types**: *array* - indica i tipo di file permessi (mimeType)
**page**: *number* - indica la pagina attuale
**perPage**: *number* - indica il numero di elementi per pagina
**search**: *string* | *null* - è il valore dell'input ricerca
**skipIds**:  *array* - indica gli eventuali id dei file già caricati nel file_upload, da non mostrare quindi nella media library

**Comment by lucamussoni** [comment]
@damiandominella alla prima chiamata non mi arrivano "page" e "perPage". cosa facciamo? tolgo il required o me li passi sempre?

**Comment by lucamussoni** [comment]
@damiandominella in "search" passa stringa vuota invece di null
