### ISSUE TITLE
Form: fare componente "gallery" (non editabile) che mostra semplicemente le immagini che vengono passate come url

### ISSUE THREAD

**Issue by lucamussoni** [MrAPPs-RSM/ngx-backend#133]
più pulsante download?

EDIT: per scaricare le thumb delle immagini vediamo come fare, perchè non so se riesco a passarle dal form. eventualmente mettiamo il solito campo endpoint con una struttura definita da noi

**Comment by damiandominella** [comment]
Creazione componente da setup.json
```json
{
  "type": "gallery",
  "label": "Gallery",
  "options": {
    "endpoint": "documents/list",
    "download": true
  }
}
```

La risposta di **endpoint** dev'essere un array di oggetti che abbiano almeno la chiave *url*.
Esempio:
```json
[
  {
    "url": "test.png"
  },
  {
    "url": "test.png"
  }
]
```
