### ISSUE TITLE
Aggiungere nuovo campo preview

### ISSUE THREAD

**Issue by samuele-mrapps** [MrAPPs-RSM/ngx-backend#59]
Deve poter mostrare un'immagine, possibilità di impostare un'url parametrizzato e dipendente da altri campi.
Esempio:

value
------
http://res.cloudinary.com/mr-apps/image/upload/c_fill,h_320,pg_:page,w_320/v1520419650/colombini-mock/vitality_pdf.jpg

parametri: page da sostituire per esempio con l'input da cui dipende (per esempio input number).

Io supporterei dipendenze multiple

**Comment by damiandominella** [comment]
JSON di configurazione (file + preview)

```json
{
	{
		"key": "fileId",
		"type": "file",
		"label": "File (en)",
		"options": {
			"api": {
				"upload": "Documents/upload"
			},
			"allowedContentTypes": [
				".png",
				".jpg",
				".jpeg",
				".gif",
				".avi",
				".mp4",
				".pdf"
			],
			"validators": {
				"required": false
			}
		}
	}, {
		"key": "thumbnailPosition",
		"type": "preview",
		"label": "Preview (en)",
		"fileKey": "fileId",
		"endpoint": "preview",
		"width": 320,
		"height": 320
	}
}
```

**Comment by lucamussoni** [comment]
Se carico un video e muovo lo slider, inizia a fare la chiamata /preview a ripetizione tra 2 valori vicini (es. secondo 5 e secondo 6, poi ancora 5, poi 6 ecc). Il video è di 66 secondi.

Con un pdf di 2 pagine nessun problema, dovrei provare con più pagine.
