### ISSUE TITLE
Le tendine dei filtri (select filters) sbarellano il layout se ci sono pochi record in tabella (e molti nella select)

### ISSUE THREAD

**Issue by lucamussoni** [MrAPPs-RSM/ngx-backend#77]
<img width="979" alt="screen shot 2018-03-27 at 16 14 26" src="https://user-images.githubusercontent.com/10722984/37973072-ff3f8974-31d9-11e8-8554-df1e6fe7ec95.png">

**Comment by samuele-mrapps** [comment]
Lo stesso si verifica anche se la tabella non ha elementi
